# Data synthesis — running parse / extract / embed / reduce on a 10% subset

Companion to [`DATASYNTHESIS.md`](DATASYNTHESIS.md) and
[`DATASETS.md`](DATASETS.md). Where those documents describe how the
synthesis side *works*, this notebook is the **end-to-end runnable
demo**: take 10% of the small Nemotron-Personas-Vietnam parquet (300K
rows × 22 columns) and push it through the same four post-generation
stages the curator uses on NSO source documents:

    parse → extract → embed → reduce

| Stage     | What it does                                             | Mirror in code                                              |
| --------- | -------------------------------------------------------- | ----------------------------------------------------------- |
| parse     | load + schema-validate + build unified narrative text    | `packages.curator.stages.ParseStage`                        |
| extract   | TF-IDF top-N keywords per persona + per region           | `packages.curator.stages.ExtractStage`                      |
| embed     | sentence-transformers (384-d) over the narrative         | `packages.personas.embed.pipeline.embed_personas`           |
| reduce    | UMAP → 2-D (HDBSCAN clustering optional, off by default) | `packages.curator.stages.ReduceStage`                       |

Every figure follows the
[NVIDIA brand guidelines](https://www.nvidia.com/en-us/about-nvidia/legal-info/logo-brand-usage/):

* **White** background
* **NVIDIA Green** `#76B900` for the primary data series
* **Black** axis chrome / **NVIDIA Sans** fallback typography

PNG snapshots land under `docs/figures/synthesis/`; the interactive
HTML lives next to each PNG so reviewers can pan / zoom / hover.

Run prerequisites:

```bash
# build the four parquets first (~5s smoke run, ~27 min full)
python -m packages.pipeline.cli build-nemotron --large-size 10000 --small-size 1000

# extras for embed + reduce + plotting
pip install -e ".[curator,viz]"

python -m scripts._build_datasynthesis_nb
jupyter nbconvert --to notebook --execute DATASYNTHESIS.ipynb \
    --inplace --ExecutePreprocessor.timeout=1800
```

Wall-clock on an M-series Mac (CPU-only, 30K-row default subset):

| Stage   | Time     |
| ------- | -------- |
| parse   | <1s      |
| extract | ~10s     |
| embed   | ~6 min   |
| reduce  | ~1-2 min |

If you want to iterate faster, dial `SAMPLE_FRAC` in §1 down (`0.01`
gives a 3K-row subset that finishes in <1 minute end to end).

## §0 — Setup

In [1]:
'''Setup — imports, NVIDIA Plotly theme, paths to the small parquet datasets.'''
from __future__ import annotations

import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio

warnings.filterwarnings('ignore')

REPO_ROOT = Path.cwd()
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts._nvidia_style import (
    apply_nvidia_style, save_figure,
    NV_GREEN, NV_GREEN_DARK, NV_GREEN_SOFT,
    NV_BLACK, NV_DARK, NV_GREY, NV_LIGHT_GREY,
    NV_WHITE, NV_DISCRETE, NV_SEQUENTIAL, NV_FONT_FAMILY,
)

DATA_DIR = REPO_ROOT / 'data' / 'Nemotron-Personas-Vietnam'
OUT_DIR  = REPO_ROOT / 'docs' / 'figures' / 'synthesis'
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Stage outputs (parsed / embedded / reduced parquets) land in a sub-
# folder so the demo never touches the canonical 300K small datasets.
SUBSET_DIR = DATA_DIR / '_subset_pipeline'
SUBSET_DIR.mkdir(parents=True, exist_ok=True)

pio.templates['nvidia'] = go.layout.Template(
    layout=go.Layout(
        paper_bgcolor='white', plot_bgcolor='white',
        font=dict(family=NV_FONT_FAMILY, color=NV_BLACK, size=13),
        colorway=NV_DISCRETE,
    )
)
pio.templates.default = 'nvidia'

print(f'data dir:   {DATA_DIR.relative_to(REPO_ROOT)}')
print(f'subset dir: {SUBSET_DIR.relative_to(REPO_ROOT)}')
print(f'figures:    {OUT_DIR.relative_to(REPO_ROOT)}')

data dir:   data/Nemotron-Personas-Vietnam
subset dir: data/Nemotron-Personas-Vietnam/_subset_pipeline
figures:    docs/figures/synthesis

## §1 — Load the small parquet & take a 10% subset

The small variant is 300K rows (10% of the published 3M ``-large-``).
Sampling 10% of *that* gives a 30K-row subset — small enough to
embed on CPU in a few minutes, large enough that the 2-D UMAP layout
captures the demographic + occupational structure.

We sample by `uuid` so the Vietnamese and English mirrors stay aligned
1-to-1 (every persona in the subset has both narrations available).

In [2]:
'''Load both small parquets (vi + en) and take a uuid-aligned 10% sample.'''
SMALL_VI = DATA_DIR / 'Nemotron-Personas-Vietnam-small-vi.parquet'
SMALL_EN = DATA_DIR / 'Nemotron-Personas-Vietnam-small-en.parquet'

df_vi_full = pd.read_parquet(SMALL_VI)
df_en_full = pd.read_parquet(SMALL_EN)
print(f'vi parquet: {df_vi_full.shape}  ({SMALL_VI.stat().st_size / 1e6:.1f} MB)')
print(f'en parquet: {df_en_full.shape}  ({SMALL_EN.stat().st_size / 1e6:.1f} MB)')

SAMPLE_FRAC = 0.10           # 10% of small = 30K rows; lower for fast iteration
SAMPLE_SEED = 20260506

sample_uuids = (
    df_vi_full['uuid']
    .sample(frac=SAMPLE_FRAC, random_state=SAMPLE_SEED)
    .sort_values()
    .reset_index(drop=True)
)
df_vi = df_vi_full[df_vi_full['uuid'].isin(sample_uuids)].reset_index(drop=True)
df_en = df_en_full[df_en_full['uuid'].isin(sample_uuids)].reset_index(drop=True)
df_vi = df_vi.sort_values('uuid').reset_index(drop=True)
df_en = df_en.sort_values('uuid').reset_index(drop=True)
assert (df_vi['uuid'].values == df_en['uuid'].values).all(), 'uuid alignment broke'
print(f'\nsubset:     {SAMPLE_FRAC:.0%}  →  {len(df_vi):,} rows  (vi + en aligned)')

# Drop the full frames so the kernel reclaims ~600MB of resident RAM.
del df_vi_full, df_en_full

vi parquet: (299999, 22)  (114.9 MB)
en parquet: (299999, 22)  (100.9 MB)

subset:     10%  →  30,000 rows  (vi + en aligned)

## §2 — Parse

The parquet's 22 columns split into three groups:

* **1 identifier** — `uuid`
* **12 narrative fields** — long natural-language strings
  (`persona`, `professional_persona`, `cultural_background`, …) plus
  two `_list` mirrors of the freeform skills / hobbies fields.
* **9 structured fields** — demographic, socio-economic, geographic.

`parse` validates the schema, summarises the column-level dtypes, and
concatenates the six freeform narrative columns into a single `text`
field — the same shape `packages.curator.stages.ParseStage` produces
for NSO source documents, so the downstream `extract` / `embed` stages
can be reused unchanged.

In [3]:
'''Parse — schema-validate the 22 columns, summarise the row, build a unified
   `text` field for embedding.'''
from packages.personas.datasets.schema import (
    NEMOTRON_PERSONAS_VIETNAM_COLUMNS,
    NEMOTRON_PERSONAS_VIETNAM_FEATURES,
)

assert tuple(df_vi.columns) == NEMOTRON_PERSONAS_VIETNAM_COLUMNS, 'unexpected column layout'
print(f'columns ({len(df_vi.columns)}):')
for col in df_vi.columns:
    dtype = NEMOTRON_PERSONAS_VIETNAM_FEATURES[col]
    sample = df_vi[col].iloc[0]
    if isinstance(sample, str) and len(sample) > 60:
        sample = sample[:57] + '…'
    print(f'  {col:32s} {dtype:6s}  e.g. {sample!r}')

# Build the unified `text` field — the six long-form narrative columns.
# (The two `_list` mirrors are excluded; their information is already
# subsumed by `skills_and_expertise` / `hobbies_and_interests`.)
NARRATIVE_COLS = [
    'persona', 'professional_persona', 'cultural_background',
    'skills_and_expertise', 'hobbies_and_interests',
    'career_goals_and_ambitions',
]
def _build_text(row: pd.Series) -> str:
    return '\n'.join(str(row[c]) for c in NARRATIVE_COLS if isinstance(row[c], str) and row[c])

parsed = df_vi.copy()
parsed['text'] = parsed.apply(_build_text, axis=1)
text_lens = parsed['text'].str.len()
print(f'\nnarrative length: median={text_lens.median():.0f}  '
      f'p95={text_lens.quantile(0.95):.0f}  max={text_lens.max():.0f}  chars')

parsed_path = SUBSET_DIR / 'parsed.parquet'
parsed.to_parquet(parsed_path, index=False)
print(f'wrote {parsed_path.relative_to(REPO_ROOT)}  (n={len(parsed):,})')

columns (22):
  uuid                             string  e.g. '0002a8f2-c66e-4406-9249-965812b7678d'
  professional_persona             string  e.g. 'Đặng An Nguyên làm việc trong nhóm nghề Thợ lắp ráp và vậ…'
  sports_persona                   string  e.g. 'Ở tuổi 31, Đặng An Nguyên duy trì sức khoẻ qua võ cổ truy…'
  arts_persona                     string  e.g. 'Đặng An Nguyên yêu thích các loại hình nghệ thuật truyền …'
  travel_persona                   string  e.g. 'Đặng An Nguyên thường nghỉ ngơi tại các điểm đến nổi tiến…'
  culinary_persona                 string  e.g. 'Đặng An Nguyên thường thưởng thức ẩm thực Đồng bằng sông …'
  persona                          string  e.g. 'Đặng An Nguyên, 31 tuổi, Nam, Chưa kết hôn, trình độ Khôn…'
  cultural_background              string  e.g. 'Đặng An Nguyên lớn lên ở khu vực Nông thôn thuộc Hà Nội (…'
  skills_and_expertise             string  e.g. 'Các kỹ năng nổi bật bao gồm: đọc đồng hồ đo và bảng điều …'
  skills_and_expertise_list        string  e.g. 'đọc đồng hồ đo và bảng điều khiển, phát hiện và xử lý sự …'
  hobbies_and_interests            string  e.g. 'Sở thích thường ngày của họ bao gồm: câu cá ở ao làng, ch…'
  hobbies_and_interests_list       string  e.g. 'câu cá ở ao làng, chăm sóc gia súc, gia cầm, chăm sóc vườ…'
  career_goals_and_ambitions       string  e.g. 'Trong vài năm tới, Đặng An Nguyên mong muốn lên vị trí ca…'
  sex                              string  e.g. 'Nam'
  age                              int64   e.g. np.int64(31)
  marital_status                   string  e.g. 'Chưa kết hôn'
  education_level                  string  e.g. 'Không có trình độ CMKT'
  occupation                       string  e.g. 'Thợ lắp ráp và vận hành máy móc, thiết bị'
  region                           string  e.g. 'Đồng bằng sông Hồng'
  area                             string  e.g. 'Nông thôn'
  province                         string  e.g. 'Hà Nội'
  country                          string  e.g. 'Việt Nam'

narrative length: median=1165  p95=1252  max=1351  chars

wrote data/Nemotron-Personas-Vietnam/_subset_pipeline/parsed.parquet  (n=30,000)

In [4]:
'''Quick demographic snapshot of the subset — sanity check that the 10%
   sample preserves the marginal shape of the parent 300K small dataset.'''
def _value_counts(col: str, top: int = 6) -> pd.DataFrame:
    s = parsed[col].value_counts(normalize=True).head(top)
    return s.mul(100).round(1).rename('%').reset_index()

snap = pd.concat({
    'sex':              _value_counts('sex'),
    'region':           _value_counts('region'),
    'education_level':  _value_counts('education_level'),
    'occupation':       _value_counts('occupation', top=5),
}, axis=1)
snap

   sex                                      region        \
   sex     %                                region     %
0   Nữ  50.5                   Đồng bằng sông Hồng  23.8
1  Nam  49.5  Bắc Trung Bộ và Duyên hải miền Trung  20.4
2  NaN   NaN                           Đông Nam Bộ  19.3
3  NaN   NaN               Đồng bằng sông Cửu Long  17.2
4  NaN   NaN         Trung du và miền núi phía Bắc  13.2
5  NaN   NaN                            Tây Nguyên   6.1

          education_level                                       occupation  \
          education_level     %                                 occupation
0  Không có trình độ CMKT  67.3                              Nghề giản đơn
1         Đại học trở lên  15.5           Dịch vụ cá nhân, bảo vệ bán hàng
2                  Sơ cấp   7.3  Thợ lắp ráp và vận hành máy móc, thiết bị
3               Trung cấp   5.1  Thợ thủ công và các thợ khác có liên quan
4                Cao đẳng   4.9                              Không áp dụng
5                     NaN   NaN                                        NaN


      %
0  23.2
1  17.9
2  12.9
3  12.6
4  10.4
5   NaN

## §3 — Extract — TF-IDF keywords

`extract` mirrors `packages.curator.stages.ExtractStage`: a
multilingual-friendly TF-IDF (with the same Unicode-aware token pattern
the curator uses, ``\b[\wÀ-ỹ]{3,}\b``) gives every narrative its
top-N keywords. Unlike the curator we don't need to map records to an
ontology domain — the parquet already carries `region` / `occupation`
/ `education_level` etc as first-class columns, so we group on those
directly.

Two views below:

1. **Per-persona top-N keywords** — a flat column we attach back to
   `parsed`.
2. **Per-region top keywords** — what tokens carry the most TF-IDF
   weight in each macro-region's narratives. The bar chart's facets
   show how the six regions diverge linguistically.

In [5]:
'''Extract — TF-IDF top-8 keywords per persona narrative.'''
from sklearn.feature_extraction.text import TfidfVectorizer

vec = TfidfVectorizer(
    max_df=0.85, min_df=5,
    ngram_range=(1, 2),
    token_pattern=r'(?u)\b[\wÀ-ỹ]{3,}\b',  # match the curator
    max_features=20000,
)
matrix = vec.fit_transform(parsed['text'])
vocab = vec.get_feature_names_out()
print(f'tfidf matrix: {matrix.shape[0]:,} docs × {matrix.shape[1]:,} terms')

TOP_N = 8
def _top_keywords(i: int) -> list[str]:
    row = matrix.getrow(i).toarray()[0]
    if not row.any():
        return []
    top = sorted(enumerate(row), key=lambda kv: -kv[1])[:TOP_N]
    return [str(vocab[j]) for j, w in top if w > 0]

parsed['keywords'] = [_top_keywords(i) for i in range(matrix.shape[0])]
parsed[['uuid', 'occupation', 'region', 'keywords']].head(5)

tfidf matrix: 30,000 docs × 8,263 terms

,uuid,occupation,region,keywords
0,0002a8f2-c66e-4406-9249-965812b7678d,"Thợ lắp ráp và vận hành máy móc, thiết bị",Đồng bằng sông Hồng,"[đặng nguyên, đặng, nguyên, nội, nội đồng, thu..."
1,0002d88f-1417-47dc-bbcc-9e9a2b13953b,Chuyên môn kỹ thuật bậc cao,Bắc Trung Bộ và Duyên hải miền Trung,"[thạch sơn, thạch, sơn, hoàng, nghệ, bản thuyế..."
2,0002fde1-e66b-4dad-b7c6-d249243c71b8,"Dịch vụ cá nhân, bảo vệ bán hàng",Bắc Trung Bộ và Duyên hải miền Trung,"[khanh, bình thuận, ngô, thuận, dịch, thuận bắ..."
3,0006df39-eec9-423c-9410-98431c488c1f,"Dịch vụ cá nhân, bảo vệ bán hàng",Bắc Trung Bộ và Duyên hải miền Trung,"[bùi vĩnh, vĩnh hải, vĩnh, bình thuận, bùi, th..."
4,0006facf-de4e-48a3-b625-55e60bba1afc,"Lao động có kỹ năng trong nông nghiệp, lâm ngh...",Đồng bằng sông Hồng,"[văn minh, quảng ninh, ninh, minh, quảng, nông..."

In [6]:
'''Top TF-IDF keywords per macro-region — what's distinctive in each
   region's persona narratives.'''
region_kw = (
    parsed[['region', 'keywords']]
    .explode('keywords').dropna(subset=['keywords'])
    .groupby(['region', 'keywords'], as_index=False).size()
    .rename(columns={'size': 'count'})
)
top_per_region = (
    region_kw.sort_values(['region', 'count'], ascending=[True, False])
             .groupby('region').head(8)
             .reset_index(drop=True)
)
fig = px.bar(
    top_per_region, x='count', y='keywords',
    facet_col='region', facet_col_wrap=3, orientation='h',
    title=f'Top TF-IDF keywords per region · 10% subset (n={len(parsed):,})',
    color_discrete_sequence=[NV_GREEN],
)
fig.update_yaxes(autorange='reversed', matches=None, showticklabels=True)
fig.update_xaxes(matches=None)
fig.for_each_annotation(lambda a: a.update(text=a.text.replace('region=', '')))
apply_nvidia_style(fig)
fig.update_layout(height=900, showlegend=False)
save_figure(fig, '01_tfidf_keywords_per_region', out_dir=OUT_DIR, height=900)
fig.show()

## §4 — Embed

`embed` runs a multilingual sentence-transformers model
(`paraphrase-multilingual-MiniLM-L12-v2`, 384-d, free + offline) over
each persona's narrative. Switching to a hosted NIM model is one line:

```python
from packages.personas.embed.backends import make_embedding_backend
backend = make_embedding_backend(
    model='nvidia/llama-3.2-nv-embedqa-1b-v2',  # 2048-d
    backend='nim',
    nim_config=NimEmbeddingsConfig(api_key_env='NVIDIA_API_KEY'),
)
```

The model id alone is enough — `backend="auto"` (the default) routes
anything starting with `nvidia/` to NIM and everything else to the
local SBERT path.

Wall-clock on an M-series Mac, CPU-only, 30K rows: **~6 minutes**.

In [7]:
'''Embed — local SBERT (384-d) over the 30K narratives.'''
from packages.personas.embed.backends import (
    LOCAL_DEFAULT_MODEL,
    make_embedding_backend,
)

EMBED_MODEL   = LOCAL_DEFAULT_MODEL              # paraphrase-multilingual-MiniLM-L12-v2
EMBED_BACKEND = 'auto'                           # auto-routes (no `nvidia/...` → local)
backend = make_embedding_backend(model=EMBED_MODEL, backend=EMBED_BACKEND, device='cpu')
print(f'backend: {backend.name}   model: {backend.model}')

# SBERT truncates at ~128 tokens (~500 chars); cap at 2000 to be safe
# without slowing the encoder.
texts = parsed['text'].str.slice(0, 2000).tolist()
vectors = backend.encode(
    texts, batch_size=64, normalize=True,
    input_type='passage', show_progress=True,
)
backend.close()
print(f'\nembedded: {vectors.shape}   dtype={vectors.dtype}')

embedded = parsed[[
    'uuid', 'sex', 'age', 'marital_status', 'education_level',
    'occupation', 'region', 'area', 'province', 'country',
]].copy()
embedded['vector'] = list(vectors)
embedded_path = SUBSET_DIR / 'embedded.parquet'
embedded.to_parquet(embedded_path, index=False)
print(f'wrote {embedded_path.relative_to(REPO_ROOT)}')

[05/08/26 09:41:44] INFO     loading local embedding model:
                             sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 (device=cpu)

[05/08/26 09:41:45] INFO     Loading SentenceTransformer model from
                             sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2.

Loading weights:   0%|                                  | 0/199 [00:00<?, ?it/s]

Loading weights: 100%|██████████████████████| 199/199 [00:00<00:00, 8817.80it/s]

backend: sentence-transformers   model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

Batches:   0%|                                          | 0/469 [00:00<?, ?it/s]

Batches:   0%|                                  | 1/469 [00:01<07:51,  1.01s/it]

Batches:   0%|▏                                 | 2/469 [00:01<06:49,  1.14it/s]

Batches:   1%|▏                                 | 3/469 [00:04<14:15,  1.84s/it]

Batches:   1%|▎                                 | 4/469 [00:06<12:37,  1.63s/it]

Batches:   1%|▎                                 | 5/469 [00:07<13:23,  1.73s/it]

Batches:   1%|▍                                 | 6/469 [00:11<18:00,  2.33s/it]

Batches:   1%|▌                                 | 7/469 [00:13<16:38,  2.16s/it]

Batches:   2%|▌                                 | 8/469 [00:16<20:00,  2.60s/it]

Batches:   2%|▋                                 | 9/469 [00:18<18:05,  2.36s/it]

Batches:   2%|▋                                | 10/469 [00:22<21:44,  2.84s/it]

Batches:   2%|▊                                | 11/469 [00:26<24:19,  3.19s/it]

Batches:   3%|▊                                | 12/469 [00:28<21:16,  2.79s/it]

Batches:   3%|▉                                | 13/469 [00:30<18:28,  2.43s/it]

Batches:   3%|▉                                | 14/469 [00:31<16:33,  2.18s/it]

Batches:   3%|█                                | 15/469 [00:33<15:11,  2.01s/it]

Batches:   3%|█▏                               | 16/469 [00:34<14:06,  1.87s/it]

Batches:   4%|█▏                               | 17/469 [00:37<15:40,  2.08s/it]

Batches:   4%|█▎                               | 18/469 [00:39<15:21,  2.04s/it]

Batches:   4%|█▎                               | 19/469 [00:41<14:45,  1.97s/it]

Batches:   4%|█▍                               | 20/469 [00:44<17:00,  2.27s/it]

Batches:   4%|█▍                               | 21/469 [00:45<15:36,  2.09s/it]

Batches:   5%|█▌                               | 22/469 [00:47<14:10,  1.90s/it]

Batches:   5%|█▌                               | 23/469 [00:49<14:03,  1.89s/it]

Batches:   5%|█▋                               | 24/469 [00:50<13:14,  1.78s/it]

Batches:   5%|█▊                               | 25/469 [00:52<12:42,  1.72s/it]

Batches:   6%|█▊                               | 26/469 [00:54<12:57,  1.75s/it]

Batches:   6%|█▉                               | 27/469 [00:55<13:03,  1.77s/it]

Batches:   6%|█▉                               | 28/469 [00:57<12:57,  1.76s/it]

Batches:   6%|██                               | 29/469 [01:00<15:06,  2.06s/it]

Batches:   6%|██                               | 30/469 [01:02<14:08,  1.93s/it]

Batches:   7%|██▏                              | 31/469 [01:04<15:47,  2.16s/it]

Batches:   7%|██▎                              | 32/469 [01:10<23:25,  3.22s/it]

Batches:   7%|██▎                              | 33/469 [01:15<26:53,  3.70s/it]

Batches:   7%|██▍                              | 34/469 [01:19<28:27,  3.93s/it]

Batches:   7%|██▍                              | 35/469 [01:23<27:08,  3.75s/it]

Batches:   8%|██▌                              | 36/469 [01:29<32:32,  4.51s/it]

Batches:   8%|██▌                              | 37/469 [01:31<28:30,  3.96s/it]

Batches:   8%|██▋                              | 38/469 [01:34<24:31,  3.42s/it]

Batches:   8%|██▋                              | 39/469 [01:35<21:01,  2.93s/it]

Batches:   9%|██▊                              | 40/469 [01:38<19:49,  2.77s/it]

Batches:   9%|██▉                              | 41/469 [01:44<26:07,  3.66s/it]

Batches:   9%|██▉                              | 42/469 [01:49<30:29,  4.28s/it]

Batches:   9%|███                              | 43/469 [01:51<25:26,  3.58s/it]

Batches:   9%|███                              | 44/469 [01:53<20:43,  2.93s/it]

Batches:  10%|███▏                             | 45/469 [01:54<17:08,  2.42s/it]

Batches:  10%|███▏                             | 46/469 [01:56<15:50,  2.25s/it]

Batches:  10%|███▎                             | 47/469 [01:58<14:55,  2.12s/it]

Batches:  10%|███▍                             | 48/469 [02:01<17:46,  2.53s/it]

Batches:  10%|███▍                             | 49/469 [02:07<24:07,  3.45s/it]

Batches:  11%|███▌                             | 50/469 [02:09<22:03,  3.16s/it]

Batches:  11%|███▌                             | 51/469 [02:14<26:41,  3.83s/it]

Batches:  11%|███▋                             | 52/469 [02:18<25:33,  3.68s/it]

Batches:  11%|███▋                             | 53/469 [02:19<20:58,  3.02s/it]

Batches:  12%|███▊                             | 54/469 [02:21<17:44,  2.57s/it]

Batches:  12%|███▊                             | 55/469 [02:24<19:44,  2.86s/it]

Batches:  12%|███▉                             | 56/469 [02:27<19:41,  2.86s/it]

Batches:  12%|████                             | 57/469 [02:29<16:53,  2.46s/it]

Batches:  12%|████                             | 58/469 [02:32<18:17,  2.67s/it]

Batches:  13%|████▏                            | 59/469 [02:34<17:14,  2.52s/it]

Batches:  13%|████▏                            | 60/469 [02:38<20:04,  2.94s/it]

Batches:  13%|████▎                            | 61/469 [02:40<18:18,  2.69s/it]

Batches:  13%|████▎                            | 62/469 [02:41<15:29,  2.28s/it]

Batches:  13%|████▍                            | 63/469 [02:44<14:59,  2.22s/it]

Batches:  14%|████▌                            | 64/469 [02:46<14:39,  2.17s/it]

Batches:  14%|████▌                            | 65/469 [02:48<14:41,  2.18s/it]

Batches:  14%|████▋                            | 66/469 [02:57<28:12,  4.20s/it]

Batches:  14%|████▋                            | 67/469 [03:03<32:25,  4.84s/it]

Batches:  14%|████▊                            | 68/469 [03:07<31:22,  4.69s/it]

Batches:  15%|████▊                            | 69/469 [03:11<28:53,  4.33s/it]

Batches:  15%|████▉                            | 70/469 [03:13<23:35,  3.55s/it]

Batches:  15%|████▉                            | 71/469 [03:16<23:08,  3.49s/it]

Batches:  15%|█████                            | 72/469 [03:22<28:18,  4.28s/it]

Batches:  16%|█████▏                           | 73/469 [03:25<24:55,  3.78s/it]

Batches:  16%|█████▏                           | 74/469 [03:27<21:12,  3.22s/it]

Batches:  16%|█████▎                           | 75/469 [03:29<18:35,  2.83s/it]

Batches:  16%|█████▎                           | 76/469 [03:30<16:40,  2.54s/it]

Batches:  16%|█████▍                           | 77/469 [03:34<18:26,  2.82s/it]

Batches:  17%|█████▍                           | 78/469 [03:37<18:41,  2.87s/it]

Batches:  17%|█████▌                           | 79/469 [03:40<20:02,  3.08s/it]

Batches:  17%|█████▋                           | 80/469 [03:48<28:45,  4.43s/it]

Batches:  17%|█████▋                           | 81/469 [03:56<36:30,  5.65s/it]

Batches:  17%|█████▊                           | 82/469 [04:02<35:53,  5.57s/it]

Batches:  18%|█████▊                           | 83/469 [04:04<28:36,  4.45s/it]

Batches:  18%|█████▉                           | 84/469 [04:06<23:36,  3.68s/it]

Batches:  18%|█████▉                           | 85/469 [04:07<19:32,  3.05s/it]

Batches:  18%|██████                           | 86/469 [04:09<16:27,  2.58s/it]

Batches:  19%|██████                           | 87/469 [04:10<14:05,  2.21s/it]

Batches:  19%|██████▏                          | 88/469 [04:11<12:14,  1.93s/it]

Batches:  19%|██████▎                          | 89/469 [04:13<11:14,  1.78s/it]

Batches:  19%|██████▎                          | 90/469 [04:16<13:25,  2.13s/it]

Batches:  19%|██████▍                          | 91/469 [04:19<15:57,  2.53s/it]

Batches:  20%|██████▍                          | 92/469 [04:21<14:52,  2.37s/it]

Batches:  20%|██████▌                          | 93/469 [04:23<14:35,  2.33s/it]

Batches:  20%|██████▌                          | 94/469 [04:25<14:08,  2.26s/it]

Batches:  20%|██████▋                          | 95/469 [04:27<13:20,  2.14s/it]

Batches:  20%|██████▊                          | 96/469 [04:29<13:14,  2.13s/it]

Batches:  21%|██████▊                          | 97/469 [04:33<16:28,  2.66s/it]

Batches:  21%|██████▉                          | 98/469 [04:37<17:37,  2.85s/it]

Batches:  21%|██████▉                          | 99/469 [04:39<16:33,  2.69s/it]

Batches:  21%|██████▊                         | 100/469 [04:41<15:14,  2.48s/it]

Batches:  22%|██████▉                         | 101/469 [04:42<12:55,  2.11s/it]

Batches:  22%|██████▉                         | 102/469 [04:43<11:18,  1.85s/it]

Batches:  22%|███████                         | 103/469 [04:45<10:15,  1.68s/it]

Batches:  22%|███████                         | 104/469 [04:46<10:23,  1.71s/it]

Batches:  22%|███████▏                        | 105/469 [04:49<12:32,  2.07s/it]

Batches:  23%|███████▏                        | 106/469 [04:52<13:08,  2.17s/it]

Batches:  23%|███████▎                        | 107/469 [04:53<11:27,  1.90s/it]

Batches:  23%|███████▎                        | 108/469 [04:54<10:22,  1.73s/it]

Batches:  23%|███████▍                        | 109/469 [04:56<09:33,  1.59s/it]

Batches:  23%|███████▌                        | 110/469 [04:57<09:02,  1.51s/it]

Batches:  24%|███████▌                        | 111/469 [04:58<08:51,  1.48s/it]

Batches:  24%|███████▋                        | 112/469 [05:00<08:28,  1.42s/it]

Batches:  24%|███████▋                        | 113/469 [05:01<08:09,  1.38s/it]

Batches:  24%|███████▊                        | 114/469 [05:02<08:17,  1.40s/it]

Batches:  25%|███████▊                        | 115/469 [05:04<08:07,  1.38s/it]

Batches:  25%|███████▉                        | 116/469 [05:05<07:53,  1.34s/it]

Batches:  25%|███████▉                        | 117/469 [05:06<08:08,  1.39s/it]

Batches:  25%|████████                        | 118/469 [05:08<08:23,  1.43s/it]

Batches:  25%|████████                        | 119/469 [05:09<08:24,  1.44s/it]

Batches:  26%|████████▏                       | 120/469 [05:11<08:32,  1.47s/it]

Batches:  26%|████████▎                       | 121/469 [05:13<09:11,  1.59s/it]

Batches:  26%|████████▎                       | 122/469 [05:16<11:40,  2.02s/it]

Batches:  26%|████████▍                       | 123/469 [05:20<15:00,  2.60s/it]

Batches:  26%|████████▍                       | 124/469 [05:22<13:32,  2.36s/it]

Batches:  27%|████████▌                       | 125/469 [05:23<12:06,  2.11s/it]

Batches:  27%|████████▌                       | 126/469 [05:25<12:03,  2.11s/it]

Batches:  27%|████████▋                       | 127/469 [05:27<11:55,  2.09s/it]

Batches:  27%|████████▋                       | 128/469 [05:29<11:04,  1.95s/it]

Batches:  28%|████████▊                       | 129/469 [05:33<13:51,  2.45s/it]

Batches:  28%|████████▊                       | 130/469 [05:36<15:08,  2.68s/it]

Batches:  28%|████████▉                       | 131/469 [05:42<21:15,  3.77s/it]

Batches:  28%|█████████                       | 132/469 [05:44<17:17,  3.08s/it]

Batches:  28%|█████████                       | 133/469 [05:45<13:57,  2.49s/it]

Batches:  29%|█████████▏                      | 134/469 [05:46<11:53,  2.13s/it]

Batches:  29%|█████████▏                      | 135/469 [05:47<10:26,  1.87s/it]

Batches:  29%|█████████▎                      | 136/469 [05:49<09:41,  1.74s/it]

Batches:  29%|█████████▎                      | 137/469 [05:50<09:42,  1.76s/it]

Batches:  29%|█████████▍                      | 138/469 [05:52<09:53,  1.79s/it]

Batches:  30%|█████████▍                      | 139/469 [05:54<10:24,  1.89s/it]

Batches:  30%|█████████▌                      | 140/469 [05:57<11:16,  2.06s/it]

Batches:  30%|█████████▌                      | 141/469 [05:58<10:10,  1.86s/it]

Batches:  30%|█████████▋                      | 142/469 [06:00<09:25,  1.73s/it]

Batches:  30%|█████████▊                      | 143/469 [06:03<12:05,  2.23s/it]

Batches:  31%|█████████▊                      | 144/469 [06:05<11:45,  2.17s/it]

Batches:  31%|█████████▉                      | 145/469 [06:07<10:59,  2.03s/it]

Batches:  31%|█████████▉                      | 146/469 [06:09<10:54,  2.03s/it]

Batches:  31%|██████████                      | 147/469 [06:11<10:14,  1.91s/it]

Batches:  32%|██████████                      | 148/469 [06:12<09:06,  1.70s/it]

Batches:  32%|██████████▏                     | 149/469 [06:13<08:29,  1.59s/it]

Batches:  32%|██████████▏                     | 150/469 [06:16<10:09,  1.91s/it]

Batches:  32%|██████████▎                     | 151/469 [06:17<09:24,  1.78s/it]

Batches:  32%|██████████▎                     | 152/469 [06:19<08:53,  1.68s/it]

Batches:  33%|██████████▍                     | 153/469 [06:20<08:38,  1.64s/it]

Batches:  33%|██████████▌                     | 154/469 [06:21<07:58,  1.52s/it]

Batches:  33%|██████████▌                     | 155/469 [06:23<07:54,  1.51s/it]

Batches:  33%|██████████▋                     | 156/469 [06:24<07:46,  1.49s/it]

Batches:  33%|██████████▋                     | 157/469 [06:26<07:24,  1.42s/it]

Batches:  34%|██████████▊                     | 158/469 [06:27<06:59,  1.35s/it]

Batches:  34%|██████████▊                     | 159/469 [06:28<06:38,  1.29s/it]

Batches:  34%|██████████▉                     | 160/469 [06:29<06:32,  1.27s/it]

Batches:  34%|██████████▉                     | 161/469 [06:30<06:36,  1.29s/it]

Batches:  35%|███████████                     | 162/469 [06:33<08:38,  1.69s/it]

Batches:  35%|███████████                     | 163/469 [06:35<08:30,  1.67s/it]

Batches:  35%|███████████▏                    | 164/469 [06:36<08:22,  1.65s/it]

Batches:  35%|███████████▎                    | 165/469 [06:38<07:53,  1.56s/it]

Batches:  35%|███████████▎                    | 166/469 [06:39<06:58,  1.38s/it]

Batches:  36%|███████████▍                    | 167/469 [06:40<06:14,  1.24s/it]

Batches:  36%|███████████▍                    | 168/469 [06:40<05:44,  1.15s/it]

Batches:  36%|███████████▌                    | 169/469 [06:41<05:22,  1.08s/it]

Batches:  36%|███████████▌                    | 170/469 [06:42<05:07,  1.03s/it]

Batches:  36%|███████████▋                    | 171/469 [06:43<05:01,  1.01s/it]

Batches:  37%|███████████▋                    | 172/469 [06:44<04:57,  1.00s/it]

Batches:  37%|███████████▊                    | 173/469 [06:45<04:56,  1.00s/it]

Batches:  37%|███████████▊                    | 174/469 [06:46<05:12,  1.06s/it]

Batches:  37%|███████████▉                    | 175/469 [06:48<05:24,  1.10s/it]

Batches:  38%|████████████                    | 176/469 [06:49<05:45,  1.18s/it]

Batches:  38%|████████████                    | 177/469 [06:50<05:42,  1.17s/it]

Batches:  38%|████████████▏                   | 178/469 [06:51<05:49,  1.20s/it]

Batches:  38%|████████████▏                   | 179/469 [06:53<05:35,  1.16s/it]

Batches:  38%|████████████▎                   | 180/469 [06:53<05:17,  1.10s/it]

Batches:  39%|████████████▎                   | 181/469 [06:54<05:02,  1.05s/it]

Batches:  39%|████████████▍                   | 182/469 [06:55<04:52,  1.02s/it]

Batches:  39%|████████████▍                   | 183/469 [06:56<04:48,  1.01s/it]

Batches:  39%|████████████▌                   | 184/469 [06:57<04:42,  1.01it/s]

Batches:  39%|████████████▌                   | 185/469 [06:59<05:01,  1.06s/it]

Batches:  40%|████████████▋                   | 186/469 [07:00<04:58,  1.06s/it]

Batches:  40%|████████████▊                   | 187/469 [07:01<04:56,  1.05s/it]

Batches:  40%|████████████▊                   | 188/469 [07:02<04:53,  1.05s/it]

Batches:  40%|████████████▉                   | 189/469 [07:03<04:58,  1.06s/it]

Batches:  41%|████████████▉                   | 190/469 [07:04<05:10,  1.11s/it]

Batches:  41%|█████████████                   | 191/469 [07:05<05:40,  1.22s/it]

Batches:  41%|█████████████                   | 192/469 [07:07<05:37,  1.22s/it]

Batches:  41%|█████████████▏                  | 193/469 [07:08<05:35,  1.22s/it]

Batches:  41%|█████████████▏                  | 194/469 [07:09<05:38,  1.23s/it]

Batches:  42%|█████████████▎                  | 195/469 [07:10<05:38,  1.23s/it]

Batches:  42%|█████████████▎                  | 196/469 [07:12<05:32,  1.22s/it]

Batches:  42%|█████████████▍                  | 197/469 [07:13<05:22,  1.19s/it]

Batches:  42%|█████████████▌                  | 198/469 [07:14<05:48,  1.28s/it]

Batches:  42%|█████████████▌                  | 199/469 [07:16<06:35,  1.46s/it]

Batches:  43%|█████████████▋                  | 200/469 [07:18<07:05,  1.58s/it]

Batches:  43%|█████████████▋                  | 201/469 [07:19<06:35,  1.48s/it]

Batches:  43%|█████████████▊                  | 202/469 [07:20<06:03,  1.36s/it]

Batches:  43%|█████████████▊                  | 203/469 [07:21<05:38,  1.27s/it]

Batches:  43%|█████████████▉                  | 204/469 [07:22<05:30,  1.25s/it]

Batches:  44%|█████████████▉                  | 205/469 [07:24<05:35,  1.27s/it]

Batches:  44%|██████████████                  | 206/469 [07:25<05:55,  1.35s/it]

Batches:  44%|██████████████                  | 207/469 [07:27<05:52,  1.35s/it]

Batches:  44%|██████████████▏                 | 208/469 [07:28<05:37,  1.29s/it]

Batches:  45%|██████████████▎                 | 209/469 [07:29<05:22,  1.24s/it]

Batches:  45%|██████████████▎                 | 210/469 [07:30<05:09,  1.19s/it]

Batches:  45%|██████████████▍                 | 211/469 [07:31<05:03,  1.18s/it]

Batches:  45%|██████████████▍                 | 212/469 [07:32<04:55,  1.15s/it]

Batches:  45%|██████████████▌                 | 213/469 [07:33<04:55,  1.15s/it]

Batches:  46%|██████████████▌                 | 214/469 [07:35<04:54,  1.15s/it]

Batches:  46%|██████████████▋                 | 215/469 [07:36<04:52,  1.15s/it]

Batches:  46%|██████████████▋                 | 216/469 [07:37<04:49,  1.15s/it]

Batches:  46%|██████████████▊                 | 217/469 [07:38<04:52,  1.16s/it]

Batches:  46%|██████████████▊                 | 218/469 [07:39<04:48,  1.15s/it]

Batches:  47%|██████████████▉                 | 219/469 [07:40<04:47,  1.15s/it]

Batches:  47%|███████████████                 | 220/469 [07:41<04:43,  1.14s/it]

Batches:  47%|███████████████                 | 221/469 [07:43<04:38,  1.12s/it]

Batches:  47%|███████████████▏                | 222/469 [07:44<04:35,  1.11s/it]

Batches:  48%|███████████████▏                | 223/469 [07:45<04:33,  1.11s/it]

Batches:  48%|███████████████▎                | 224/469 [07:46<04:38,  1.14s/it]

Batches:  48%|███████████████▎                | 225/469 [07:47<04:46,  1.18s/it]

Batches:  48%|███████████████▍                | 226/469 [07:49<04:57,  1.22s/it]

Batches:  48%|███████████████▍                | 227/469 [07:50<04:53,  1.21s/it]

Batches:  49%|███████████████▌                | 228/469 [07:51<04:45,  1.18s/it]

Batches:  49%|███████████████▌                | 229/469 [07:52<04:52,  1.22s/it]

Batches:  49%|███████████████▋                | 230/469 [07:53<04:48,  1.21s/it]

Batches:  49%|███████████████▊                | 231/469 [07:54<04:40,  1.18s/it]

Batches:  49%|███████████████▊                | 232/469 [07:56<04:33,  1.15s/it]

Batches:  50%|███████████████▉                | 233/469 [07:57<04:36,  1.17s/it]

Batches:  50%|███████████████▉                | 234/469 [07:58<05:13,  1.33s/it]

Batches:  50%|████████████████                | 235/469 [08:00<05:30,  1.41s/it]

Batches:  50%|████████████████                | 236/469 [08:02<05:39,  1.46s/it]

Batches:  51%|████████████████▏               | 237/469 [08:03<05:26,  1.41s/it]

Batches:  51%|████████████████▏               | 238/469 [08:04<05:09,  1.34s/it]

Batches:  51%|████████████████▎               | 239/469 [08:05<04:56,  1.29s/it]

Batches:  51%|████████████████▍               | 240/469 [08:06<04:51,  1.27s/it]

Batches:  51%|████████████████▍               | 241/469 [08:08<04:39,  1.22s/it]

Batches:  52%|████████████████▌               | 242/469 [08:09<04:37,  1.22s/it]

Batches:  52%|████████████████▌               | 243/469 [08:10<05:00,  1.33s/it]

Batches:  52%|████████████████▋               | 244/469 [08:12<05:20,  1.42s/it]

Batches:  52%|████████████████▋               | 245/469 [08:13<05:10,  1.39s/it]

Batches:  52%|████████████████▊               | 246/469 [08:16<06:24,  1.72s/it]

Batches:  53%|████████████████▊               | 247/469 [08:20<08:50,  2.39s/it]

Batches:  53%|████████████████▉               | 248/469 [08:22<09:08,  2.48s/it]

Batches:  53%|████████████████▉               | 249/469 [08:24<07:47,  2.12s/it]

Batches:  53%|█████████████████               | 250/469 [08:26<07:37,  2.09s/it]

Batches:  54%|█████████████████▏              | 251/469 [08:31<10:35,  2.92s/it]

Batches:  54%|█████████████████▏              | 252/469 [08:33<10:11,  2.82s/it]

Batches:  54%|█████████████████▎              | 253/469 [08:35<09:21,  2.60s/it]

Batches:  54%|█████████████████▎              | 254/469 [08:37<07:53,  2.20s/it]

Batches:  54%|█████████████████▍              | 255/469 [08:38<06:35,  1.85s/it]

Batches:  55%|█████████████████▍              | 256/469 [08:39<05:36,  1.58s/it]

Batches:  55%|█████████████████▌              | 257/469 [08:39<04:53,  1.38s/it]

Batches:  55%|█████████████████▌              | 258/469 [08:41<04:31,  1.29s/it]

Batches:  55%|█████████████████▋              | 259/469 [08:42<04:18,  1.23s/it]

Batches:  55%|█████████████████▋              | 260/469 [08:43<04:09,  1.20s/it]

Batches:  56%|█████████████████▊              | 261/469 [08:44<04:02,  1.17s/it]

Batches:  56%|█████████████████▉              | 262/469 [08:45<03:54,  1.13s/it]

Batches:  56%|█████████████████▉              | 263/469 [08:46<03:44,  1.09s/it]

Batches:  56%|██████████████████              | 264/469 [08:47<03:39,  1.07s/it]

Batches:  57%|██████████████████              | 265/469 [08:48<03:40,  1.08s/it]

Batches:  57%|██████████████████▏             | 266/469 [08:49<03:41,  1.09s/it]

Batches:  57%|██████████████████▏             | 267/469 [08:50<03:40,  1.09s/it]

Batches:  57%|██████████████████▎             | 268/469 [08:51<03:42,  1.11s/it]

Batches:  57%|██████████████████▎             | 269/469 [08:52<03:38,  1.09s/it]

Batches:  58%|██████████████████▍             | 270/469 [08:54<03:40,  1.11s/it]

Batches:  58%|██████████████████▍             | 271/469 [08:56<04:56,  1.50s/it]

Batches:  58%|██████████████████▌             | 272/469 [08:57<04:34,  1.39s/it]

Batches:  58%|██████████████████▋             | 273/469 [08:58<04:08,  1.27s/it]

Batches:  58%|██████████████████▋             | 274/469 [08:59<03:49,  1.18s/it]

Batches:  59%|██████████████████▊             | 275/469 [09:00<03:37,  1.12s/it]

Batches:  59%|██████████████████▊             | 276/469 [09:01<03:37,  1.13s/it]

Batches:  59%|██████████████████▉             | 277/469 [09:02<03:32,  1.10s/it]

Batches:  59%|██████████████████▉             | 278/469 [09:03<03:25,  1.08s/it]

Batches:  59%|███████████████████             | 279/469 [09:04<03:18,  1.04s/it]

Batches:  60%|███████████████████             | 280/469 [09:05<03:16,  1.04s/it]

Batches:  60%|███████████████████▏            | 281/469 [09:06<03:20,  1.07s/it]

Batches:  60%|███████████████████▏            | 282/469 [09:07<03:15,  1.04s/it]

Batches:  60%|███████████████████▎            | 283/469 [09:08<03:09,  1.02s/it]

Batches:  61%|███████████████████▍            | 284/469 [09:09<03:05,  1.00s/it]

Batches:  61%|███████████████████▍            | 285/469 [09:10<02:59,  1.02it/s]

Batches:  61%|███████████████████▌            | 286/469 [09:11<02:57,  1.03it/s]

Batches:  61%|███████████████████▌            | 287/469 [09:12<02:54,  1.04it/s]

Batches:  61%|███████████████████▋            | 288/469 [09:13<02:56,  1.03it/s]

Batches:  62%|███████████████████▋            | 289/469 [09:14<03:08,  1.05s/it]

Batches:  62%|███████████████████▊            | 290/469 [09:15<03:05,  1.04s/it]

Batches:  62%|███████████████████▊            | 291/469 [09:16<02:59,  1.01s/it]

Batches:  62%|███████████████████▉            | 292/469 [09:17<02:54,  1.02it/s]

Batches:  62%|███████████████████▉            | 293/469 [09:18<02:54,  1.01it/s]

Batches:  63%|████████████████████            | 294/469 [09:19<02:54,  1.00it/s]

Batches:  63%|████████████████████▏           | 295/469 [09:20<02:53,  1.00it/s]

Batches:  63%|████████████████████▏           | 296/469 [09:21<02:50,  1.01it/s]

Batches:  63%|████████████████████▎           | 297/469 [09:22<02:54,  1.01s/it]

Batches:  64%|████████████████████▎           | 298/469 [09:23<02:57,  1.04s/it]

Batches:  64%|████████████████████▍           | 299/469 [09:24<02:54,  1.03s/it]

Batches:  64%|████████████████████▍           | 300/469 [09:26<03:08,  1.12s/it]

Batches:  64%|████████████████████▌           | 301/469 [09:27<03:06,  1.11s/it]

Batches:  64%|████████████████████▌           | 302/469 [09:28<03:00,  1.08s/it]

Batches:  65%|████████████████████▋           | 303/469 [09:29<02:53,  1.05s/it]

Batches:  65%|████████████████████▋           | 304/469 [09:30<02:48,  1.02s/it]

Batches:  65%|████████████████████▊           | 305/469 [09:31<02:42,  1.01it/s]

Batches:  65%|████████████████████▉           | 306/469 [09:32<02:38,  1.03it/s]

Batches:  65%|████████████████████▉           | 307/469 [09:33<02:35,  1.04it/s]

Batches:  66%|█████████████████████           | 308/469 [09:34<02:36,  1.03it/s]

Batches:  66%|█████████████████████           | 309/469 [09:35<02:38,  1.01it/s]

Batches:  66%|█████████████████████▏          | 310/469 [09:36<02:57,  1.12s/it]

Batches:  66%|█████████████████████▏          | 311/469 [09:37<03:04,  1.17s/it]

Batches:  67%|█████████████████████▎          | 312/469 [09:38<03:00,  1.15s/it]

Batches:  67%|█████████████████████▎          | 313/469 [09:39<02:54,  1.12s/it]

Batches:  67%|█████████████████████▍          | 314/469 [09:41<02:54,  1.12s/it]

Batches:  67%|█████████████████████▍          | 315/469 [09:42<02:59,  1.16s/it]

Batches:  67%|█████████████████████▌          | 316/469 [09:43<02:53,  1.14s/it]

Batches:  68%|█████████████████████▋          | 317/469 [09:44<02:44,  1.08s/it]

Batches:  68%|█████████████████████▋          | 318/469 [09:45<02:35,  1.03s/it]

Batches:  68%|█████████████████████▊          | 319/469 [09:46<02:30,  1.00s/it]

Batches:  68%|█████████████████████▊          | 320/469 [09:47<02:27,  1.01it/s]

Batches:  68%|█████████████████████▉          | 321/469 [09:48<02:25,  1.02it/s]

Batches:  69%|█████████████████████▉          | 322/469 [09:49<02:25,  1.01it/s]

Batches:  69%|██████████████████████          | 323/469 [09:50<02:22,  1.02it/s]

Batches:  69%|██████████████████████          | 324/469 [09:51<02:19,  1.04it/s]

Batches:  69%|██████████████████████▏         | 325/469 [09:51<02:17,  1.05it/s]

Batches:  70%|██████████████████████▏         | 326/469 [09:52<02:18,  1.03it/s]

Batches:  70%|██████████████████████▎         | 327/469 [09:54<02:21,  1.00it/s]

Batches:  70%|██████████████████████▍         | 328/469 [09:55<02:23,  1.02s/it]

Batches:  70%|██████████████████████▍         | 329/469 [09:56<02:31,  1.08s/it]

Batches:  70%|██████████████████████▌         | 330/469 [09:57<02:29,  1.08s/it]

Batches:  71%|██████████████████████▌         | 331/469 [09:58<02:24,  1.05s/it]

Batches:  71%|██████████████████████▋         | 332/469 [09:59<02:18,  1.01s/it]

Batches:  71%|██████████████████████▋         | 333/469 [10:00<02:14,  1.01it/s]

Batches:  71%|██████████████████████▊         | 334/469 [10:01<02:12,  1.02it/s]

Batches:  71%|██████████████████████▊         | 335/469 [10:02<02:11,  1.02it/s]

Batches:  72%|██████████████████████▉         | 336/469 [10:03<02:09,  1.03it/s]

Batches:  72%|██████████████████████▉         | 337/469 [10:04<02:12,  1.00s/it]

Batches:  72%|███████████████████████         | 338/469 [10:05<02:20,  1.07s/it]

Batches:  72%|███████████████████████▏        | 339/469 [10:06<02:24,  1.11s/it]

Batches:  72%|███████████████████████▏        | 340/469 [10:07<02:26,  1.13s/it]

Batches:  73%|███████████████████████▎        | 341/469 [10:09<02:38,  1.24s/it]

Batches:  73%|███████████████████████▎        | 342/469 [10:10<02:37,  1.24s/it]

Batches:  73%|███████████████████████▍        | 343/469 [10:11<02:33,  1.22s/it]

Batches:  73%|███████████████████████▍        | 344/469 [10:12<02:34,  1.24s/it]

Batches:  74%|███████████████████████▌        | 345/469 [10:14<02:30,  1.22s/it]

Batches:  74%|███████████████████████▌        | 346/469 [10:16<03:00,  1.47s/it]

Batches:  74%|███████████████████████▋        | 347/469 [10:17<02:46,  1.36s/it]

Batches:  74%|███████████████████████▋        | 348/469 [10:18<02:33,  1.27s/it]

Batches:  74%|███████████████████████▊        | 349/469 [10:19<02:20,  1.17s/it]

Batches:  75%|███████████████████████▉        | 350/469 [10:20<02:11,  1.10s/it]

Batches:  75%|███████████████████████▉        | 351/469 [10:21<02:05,  1.06s/it]

Batches:  75%|████████████████████████        | 352/469 [10:22<02:05,  1.07s/it]

Batches:  75%|████████████████████████        | 353/469 [10:23<02:05,  1.08s/it]

Batches:  75%|████████████████████████▏       | 354/469 [10:24<02:12,  1.15s/it]

Batches:  76%|████████████████████████▏       | 355/469 [10:26<02:23,  1.25s/it]

Batches:  76%|████████████████████████▎       | 356/469 [10:27<02:25,  1.29s/it]

Batches:  76%|████████████████████████▎       | 357/469 [10:28<02:22,  1.27s/it]

Batches:  76%|████████████████████████▍       | 358/469 [10:29<02:14,  1.21s/it]

Batches:  77%|████████████████████████▍       | 359/469 [10:30<02:08,  1.17s/it]

Batches:  77%|████████████████████████▌       | 360/469 [10:31<02:02,  1.13s/it]

Batches:  77%|████████████████████████▋       | 361/469 [10:33<02:01,  1.12s/it]

Batches:  77%|████████████████████████▋       | 362/469 [10:34<01:59,  1.12s/it]

Batches:  77%|████████████████████████▊       | 363/469 [10:35<01:59,  1.13s/it]

Batches:  78%|████████████████████████▊       | 364/469 [10:36<02:01,  1.15s/it]

Batches:  78%|████████████████████████▉       | 365/469 [10:37<02:00,  1.16s/it]

Batches:  78%|████████████████████████▉       | 366/469 [10:38<02:01,  1.18s/it]

Batches:  78%|█████████████████████████       | 367/469 [10:40<02:01,  1.19s/it]

Batches:  78%|█████████████████████████       | 368/469 [10:41<01:57,  1.16s/it]

Batches:  79%|█████████████████████████▏      | 369/469 [10:42<01:54,  1.14s/it]

Batches:  79%|█████████████████████████▏      | 370/469 [10:43<01:50,  1.12s/it]

Batches:  79%|█████████████████████████▎      | 371/469 [10:44<01:48,  1.11s/it]

Batches:  79%|█████████████████████████▍      | 372/469 [10:45<01:51,  1.15s/it]

Batches:  80%|█████████████████████████▍      | 373/469 [10:47<01:56,  1.22s/it]

Batches:  80%|█████████████████████████▌      | 374/469 [10:48<02:11,  1.39s/it]

Batches:  80%|█████████████████████████▌      | 375/469 [10:51<02:37,  1.68s/it]

Batches:  80%|█████████████████████████▋      | 376/469 [10:52<02:31,  1.63s/it]

Batches:  80%|█████████████████████████▋      | 377/469 [10:54<02:22,  1.55s/it]

Batches:  81%|█████████████████████████▊      | 378/469 [10:55<02:19,  1.54s/it]

Batches:  81%|█████████████████████████▊      | 379/469 [10:56<02:10,  1.45s/it]

Batches:  81%|█████████████████████████▉      | 380/469 [10:58<01:58,  1.34s/it]

Batches:  81%|█████████████████████████▉      | 381/469 [10:59<02:06,  1.44s/it]

Batches:  81%|██████████████████████████      | 382/469 [11:01<02:10,  1.50s/it]

Batches:  82%|██████████████████████████▏     | 383/469 [11:02<01:57,  1.37s/it]

Batches:  82%|██████████████████████████▏     | 384/469 [11:03<01:45,  1.24s/it]

Batches:  82%|██████████████████████████▎     | 385/469 [11:04<01:37,  1.17s/it]

Batches:  82%|██████████████████████████▎     | 386/469 [11:05<01:35,  1.15s/it]

Batches:  83%|██████████████████████████▍     | 387/469 [11:06<01:36,  1.17s/it]

Batches:  83%|██████████████████████████▍     | 388/469 [11:07<01:32,  1.14s/it]

Batches:  83%|██████████████████████████▌     | 389/469 [11:08<01:30,  1.13s/it]

Batches:  83%|██████████████████████████▌     | 390/469 [11:09<01:27,  1.10s/it]

Batches:  83%|██████████████████████████▋     | 391/469 [11:10<01:23,  1.08s/it]

Batches:  84%|██████████████████████████▋     | 392/469 [11:11<01:23,  1.08s/it]

Batches:  84%|██████████████████████████▊     | 393/469 [11:12<01:20,  1.06s/it]

Batches:  84%|██████████████████████████▉     | 394/469 [11:14<01:20,  1.07s/it]

Batches:  84%|██████████████████████████▉     | 395/469 [11:15<01:30,  1.22s/it]

Batches:  84%|███████████████████████████     | 396/469 [11:17<01:34,  1.29s/it]

Batches:  85%|███████████████████████████     | 397/469 [11:18<01:30,  1.26s/it]

Batches:  85%|███████████████████████████▏    | 398/469 [11:19<01:25,  1.21s/it]

Batches:  85%|███████████████████████████▏    | 399/469 [11:20<01:19,  1.13s/it]

Batches:  85%|███████████████████████████▎    | 400/469 [11:21<01:15,  1.10s/it]

Batches:  86%|███████████████████████████▎    | 401/469 [11:22<01:12,  1.07s/it]

Batches:  86%|███████████████████████████▍    | 402/469 [11:24<01:25,  1.27s/it]

Batches:  86%|███████████████████████████▍    | 403/469 [11:28<02:22,  2.15s/it]

Batches:  86%|███████████████████████████▌    | 404/469 [11:32<02:58,  2.74s/it]

Batches:  86%|███████████████████████████▋    | 405/469 [11:36<03:23,  3.17s/it]

Batches:  87%|███████████████████████████▋    | 406/469 [11:42<04:03,  3.86s/it]

Batches:  87%|███████████████████████████▊    | 407/469 [11:45<03:53,  3.77s/it]

Batches:  87%|███████████████████████████▊    | 408/469 [11:51<04:25,  4.35s/it]

Batches:  87%|███████████████████████████▉    | 409/469 [11:59<05:23,  5.39s/it]

Batches:  87%|███████████████████████████▉    | 410/469 [12:04<05:08,  5.23s/it]

Batches:  88%|████████████████████████████    | 411/469 [12:08<04:51,  5.03s/it]

Batches:  88%|████████████████████████████    | 412/469 [12:15<05:18,  5.58s/it]

Batches:  88%|████████████████████████████▏   | 413/469 [12:19<04:54,  5.26s/it]

Batches:  88%|████████████████████████████▏   | 414/469 [12:24<04:39,  5.09s/it]

Batches:  88%|████████████████████████████▎   | 415/469 [12:28<04:06,  4.57s/it]

Batches:  89%|████████████████████████████▍   | 416/469 [12:32<04:04,  4.60s/it]

Batches:  89%|████████████████████████████▍   | 417/469 [12:36<03:45,  4.33s/it]

Batches:  89%|████████████████████████████▌   | 418/469 [12:39<03:23,  3.99s/it]

Batches:  89%|████████████████████████████▌   | 419/469 [12:42<02:56,  3.53s/it]

Batches:  90%|████████████████████████████▋   | 420/469 [12:44<02:44,  3.35s/it]

Batches:  90%|████████████████████████████▋   | 421/469 [12:47<02:31,  3.16s/it]

Batches:  90%|████████████████████████████▊   | 422/469 [12:53<03:01,  3.87s/it]

Batches:  90%|████████████████████████████▊   | 423/469 [12:57<02:58,  3.89s/it]

Batches:  90%|████████████████████████████▉   | 424/469 [13:06<04:09,  5.54s/it]

Batches:  91%|████████████████████████████▉   | 425/469 [13:12<04:08,  5.65s/it]

Batches:  91%|█████████████████████████████   | 426/469 [13:18<04:08,  5.77s/it]

Batches:  91%|█████████████████████████████▏  | 427/469 [13:24<04:01,  5.75s/it]

Batches:  91%|█████████████████████████████▏  | 428/469 [13:28<03:42,  5.44s/it]

Batches:  91%|█████████████████████████████▎  | 429/469 [13:33<03:30,  5.26s/it]

Batches:  92%|█████████████████████████████▎  | 430/469 [13:37<03:13,  4.95s/it]

Batches:  92%|█████████████████████████████▍  | 431/469 [13:42<02:57,  4.68s/it]

Batches:  92%|█████████████████████████████▍  | 432/469 [13:46<02:45,  4.47s/it]

Batches:  92%|█████████████████████████████▌  | 433/469 [13:51<02:52,  4.79s/it]

Batches:  93%|█████████████████████████████▌  | 434/469 [13:55<02:43,  4.66s/it]

Batches:  93%|█████████████████████████████▋  | 435/469 [14:01<02:50,  5.03s/it]

Batches:  93%|█████████████████████████████▋  | 436/469 [14:05<02:36,  4.75s/it]

Batches:  93%|█████████████████████████████▊  | 437/469 [14:09<02:23,  4.47s/it]

Batches:  93%|█████████████████████████████▉  | 438/469 [14:13<02:13,  4.30s/it]

Batches:  94%|█████████████████████████████▉  | 439/469 [14:17<02:07,  4.24s/it]

Batches:  94%|██████████████████████████████  | 440/469 [14:22<02:06,  4.37s/it]

Batches:  94%|██████████████████████████████  | 441/469 [14:25<01:54,  4.07s/it]

Batches:  94%|██████████████████████████████▏ | 442/469 [14:30<01:57,  4.34s/it]

Batches:  94%|██████████████████████████████▏ | 443/469 [14:35<01:54,  4.39s/it]

Batches:  95%|██████████████████████████████▎ | 444/469 [14:40<01:56,  4.65s/it]

Batches:  95%|██████████████████████████████▎ | 445/469 [14:48<02:18,  5.77s/it]

Batches:  95%|██████████████████████████████▍ | 446/469 [14:55<02:20,  6.12s/it]

Batches:  95%|██████████████████████████████▍ | 447/469 [14:59<02:00,  5.48s/it]

Batches:  96%|██████████████████████████████▌ | 448/469 [15:04<01:49,  5.21s/it]

Batches:  96%|██████████████████████████████▋ | 449/469 [15:08<01:39,  4.96s/it]

Batches:  96%|██████████████████████████████▋ | 450/469 [15:13<01:33,  4.92s/it]

Batches:  96%|██████████████████████████████▊ | 451/469 [15:20<01:40,  5.59s/it]

Batches:  96%|██████████████████████████████▊ | 452/469 [15:26<01:36,  5.69s/it]

Batches:  97%|██████████████████████████████▉ | 453/469 [15:30<01:20,  5.00s/it]

Batches:  97%|██████████████████████████████▉ | 454/469 [15:33<01:09,  4.65s/it]

Batches:  97%|███████████████████████████████ | 455/469 [15:38<01:04,  4.58s/it]

Batches:  97%|███████████████████████████████ | 456/469 [15:43<01:03,  4.91s/it]

Batches:  97%|███████████████████████████████▏| 457/469 [15:47<00:54,  4.56s/it]

Batches:  98%|███████████████████████████████▏| 458/469 [15:53<00:54,  4.98s/it]

Batches:  98%|███████████████████████████████▎| 459/469 [16:00<00:54,  5.49s/it]

Batches:  98%|███████████████████████████████▍| 460/469 [16:07<00:52,  5.84s/it]

Batches:  98%|███████████████████████████████▍| 461/469 [16:13<00:47,  5.91s/it]

Batches:  99%|███████████████████████████████▌| 462/469 [16:21<00:45,  6.52s/it]

Batches:  99%|███████████████████████████████▌| 463/469 [16:25<00:35,  5.97s/it]

Batches:  99%|███████████████████████████████▋| 464/469 [16:28<00:25,  5.07s/it]

Batches:  99%|███████████████████████████████▋| 465/469 [16:32<00:19,  4.77s/it]

Batches:  99%|███████████████████████████████▊| 466/469 [16:37<00:14,  4.83s/it]

Batches: 100%|███████████████████████████████▊| 467/469 [16:42<00:09,  4.79s/it]

Batches: 100%|███████████████████████████████▉| 468/469 [16:46<00:04,  4.67s/it]

Batches: 100%|████████████████████████████████| 469/469 [16:52<00:00,  4.89s/it]

Batches: 100%|████████████████████████████████| 469/469 [16:52<00:00,  2.16s/it]

embedded: (30000, 384)   dtype=float32

wrote data/Nemotron-Personas-Vietnam/_subset_pipeline/embedded.parquet

## §5 — Reduce — UMAP → 2-D (clustering optional)

`reduce` always projects the 384-d vectors to 2-D for plotting via
UMAP. **Density-based HDBSCAN clustering is optional** and matches
the production pipeline default (`packages.personas.embed.pipeline.PersonaEmbedConfig.cluster=False`,
`configs/curator.yaml` `reduce.cluster: false`, `embed-personas
--cluster` opt-in). The four scatter plots in §6 colour by raw
persona columns regardless, so clustering is only useful if you
want the §7 *modal-demographic-per-cluster* summary table.

Flip `CLUSTER = True` in the cell below to additionally compute
[HDBSCAN](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.HDBSCAN.html)
labels. We pick HDBSCAN over KMeans because it (1) discovers cluster
count from local density instead of demanding a fixed `k`, (2)
tolerates non-spherical cluster shapes, and (3) labels low-density
points as noise (`-1`) rather than forcing every persona into a
cluster.

In [8]:
'''Reduce — UMAP project to 2-D, optionally HDBSCAN cluster the 384-d vectors.

``CLUSTER`` is the opt-in toggle that mirrors the production pipeline.
Default is ``False`` — only the 2-D UMAP coords get written. Flip to
``True`` to additionally compute HDBSCAN cluster labels and add a
``cluster`` column to ``reduced.parquet`` (see §7 below).
'''
import umap

CLUSTER = False     # pipeline default — flip to True for §7 cluster summary

X = np.stack(embedded['vector'].to_list())
print(f'input: {X.shape}')

reducer = umap.UMAP(
    n_components=2, n_neighbors=25, min_dist=0.10,
    metric='cosine', random_state=20260506,
)
coords = reducer.fit_transform(X)
print(f'UMAP coords: {coords.shape}')

reduced = embedded.drop(columns=['vector']).copy()
reduced['x'] = coords[:, 0]
reduced['y'] = coords[:, 1]

if CLUSTER:
    from sklearn.cluster import HDBSCAN

    # min_cluster_size scales with the corpus so a 30K-row subset gets
    # ~30-50 clusters of ~375 personas each.
    MIN_CLUSTER_SIZE = max(5, X.shape[0] // 80)
    MIN_SAMPLES      = max(3, MIN_CLUSTER_SIZE // 4)
    clusters = HDBSCAN(
        min_cluster_size=MIN_CLUSTER_SIZE,
        min_samples=MIN_SAMPLES,
        metric='euclidean',
        cluster_selection_method='eom',
    ).fit_predict(X)
    n_dense = int(clusters.max()) + 1 if (clusters >= 0).any() else 0
    n_noise = int((clusters == -1).sum())
    print(f'HDBSCAN:    min_cluster_size={MIN_CLUSTER_SIZE}, min_samples={MIN_SAMPLES}')
    print(f'  found {n_dense} clusters + {n_noise} noise points '
          f'({n_noise / len(clusters):.1%} of input)')
    reduced['cluster'] = clusters
else:
    print('clustering: off (pipeline default — see §5 prose to opt in)')

reduced_path = SUBSET_DIR / 'reduced.parquet'
reduced.to_parquet(reduced_path, index=False)
print(f'wrote {reduced_path.relative_to(REPO_ROOT)}')

input: (30000, 384)

UMAP coords: (30000, 2)
clustering: off (pipeline default — see §5 prose to opt in)

wrote data/Nemotron-Personas-Vietnam/_subset_pipeline/reduced.parquet

## §6 — Visualise the 2-D semantic map

Four UMAP scatter plots, all on the same `(x, y)` layout and same
fixed canvas, coloured by **structured persona columns** (not by the
discovered HDBSCAN cluster) so each view lines up directly with one
axis of the 22-column schema:

* §6.1 — `region` — six NSO macro-regions
* §6.2 — `occupation` — 10-class ISCO breakdown
* §6.3 — `education_level` — five-step qualification ladder
* §6.4 — `area` — urban / rural

The discovered HDBSCAN clusters are surfaced separately in §7 as a
cluster-vs-data summary table — this section is exclusively about
how each *raw* persona attribute manifests in the embedding.

We sub-sample to 6K points for the HTML/PNG so the inline render
stays light; the underlying `reduced.parquet` keeps every row.

In [9]:
'''Helper — UMAP scatter coloured by an arbitrary categorical column.

Every embedding figure in §6 shares the same canvas + margins so the
four views line up exactly side-by-side in DATASYNTHESIS.md, and long
Vietnamese-English category names (e.g. ``Bắc Trung Bộ và Duyên hải
miền Trung``, ``Lao động có kỹ năng trong nông nghiệp...``) wrap onto
multiple legend lines so the legend never overflows the canvas.
'''
EMBED_FIG_W   = 1100        # px — fixed canvas width
EMBED_FIG_H   = 720         # px — fixed canvas height
EMBED_MARGIN  = dict(l=80, r=40, t=80, b=260)   # bottom-heavy: legend lives there
WRAP_AT       = 30          # break long legend labels every ~30 chars
PLOT_SAMPLE   = min(6000, len(reduced))         # cap for inline rendering


def _wrap(label, max_chars: int = WRAP_AT) -> str:
    '''Word-aware <br> insertion so a long category label wraps onto
    multiple legend lines without ever splitting a token.'''
    if not isinstance(label, str) or len(label) <= max_chars:
        return str(label)
    out, cur = [], ''
    for w in label.split():
        if cur and len(cur) + 1 + len(w) > max_chars:
            out.append(cur); cur = w
        else:
            cur = (cur + ' ' + w).strip()
    if cur:
        out.append(cur)
    return '<br>'.join(out)


def _scatter(color_col: str, title: str) -> go.Figure:
    df_plot = reduced.sample(PLOT_SAMPLE, random_state=20260506).copy()
    df_plot['_legend'] = df_plot[color_col].map(_wrap)
    legend_order = sorted(df_plot['_legend'].unique())
    fig = px.scatter(
        df_plot, x='x', y='y', color='_legend',
        title=title, opacity=0.7,
        color_discrete_sequence=NV_DISCRETE,
        category_orders={'_legend': legend_order},
        hover_data={
            'occupation': True, 'region': True, 'education_level': True,
            '_legend': False, 'x': False, 'y': False,
        },
    )
    fig.update_traces(marker=dict(size=4, line=dict(width=0)))
    fig.update_xaxes(title='UMAP-x')
    fig.update_yaxes(title='UMAP-y')
    apply_nvidia_style(fig)
    fig.update_layout(
        width=EMBED_FIG_W, height=EMBED_FIG_H,
        margin=EMBED_MARGIN,
        legend=dict(
            title='', orientation='h',
            yanchor='top', y=-0.15,
            xanchor='center', x=0.5,
            font=dict(size=11),
            tracegroupgap=4,
            itemsizing='constant',
        ),
    )
    return fig

In [10]:
fig = _scatter('region', 'UMAP — coloured by macro-region')
save_figure(fig, '02_umap_by_region', out_dir=OUT_DIR,
             width=EMBED_FIG_W, height=EMBED_FIG_H)
fig.show()

In [11]:
fig = _scatter('occupation', 'UMAP — coloured by occupation (10-class ISCO)')
save_figure(fig, '03_umap_by_occupation', out_dir=OUT_DIR,
             width=EMBED_FIG_W, height=EMBED_FIG_H)
fig.show()

In [12]:
fig = _scatter('education_level', 'UMAP — coloured by education level')
save_figure(fig, '04_umap_by_education', out_dir=OUT_DIR,
             width=EMBED_FIG_W, height=EMBED_FIG_H)
fig.show()

In [13]:
fig = _scatter('area', 'UMAP — coloured by area (urban / rural)')
save_figure(fig, '05_umap_by_area', out_dir=OUT_DIR,
             width=EMBED_FIG_W, height=EMBED_FIG_H)
fig.show()

## §7 — What's in each HDBSCAN cluster (only if §5 `CLUSTER=True`)

HDBSCAN is unsupervised — it doesn't know the structured persona
columns exist, and unlike KMeans it doesn't force every point into
a cluster. The most useful sanity check is to look at the **modal
demographics inside each cluster**: if the embedding learned
something real about the narrative, clusters should split cleanly on
high-information axes (occupation > region > education > area).

Cluster id ``-1`` collects the noise points HDBSCAN couldn't
confidently assign — we drop those from the summary so the table
only describes the dense regions of the embedding.

This cell is a no-op when §5 ran with the pipeline default
(`CLUSTER = False`); flip §5's toggle on, re-execute it, and re-run
this cell to populate the summary table.

In [14]:
'''Modal demographic profile per HDBSCAN cluster (noise dropped).

Skips with a printed message if §5 ran with ``CLUSTER = False`` — i.e.
``reduced.parquet`` has no ``cluster`` column. Flip §5's toggle and
re-run §5 + §7 to populate the table.
'''
if 'cluster' not in reduced.columns:
    cluster_summary = None
    print('clustering: off (re-run §5 with CLUSTER=True to populate this summary)')
else:
    def _mode(s: pd.Series) -> str:
        m = s.mode()
        return str(m.iat[0]) if not m.empty else ''

    dense = reduced[reduced['cluster'] != -1]
    cluster_summary = (
        dense.groupby('cluster')
             .agg(n=('uuid', 'size'),
                  top_region=('region', _mode),
                  top_occupation=('occupation', _mode),
                  top_education=('education_level', _mode),
                  top_area=('area', _mode))
             .reset_index()
             .sort_values('n', ascending=False)
             .reset_index(drop=True)
    )
    print(f'  dense clusters: {len(cluster_summary)}   '
          f'noise rows dropped: {(reduced["cluster"] == -1).sum():,} '
          f'({(reduced["cluster"] == -1).mean():.1%} of subset)')
cluster_summary

clustering: off (re-run §5 with CLUSTER=True to populate this summary)

---

## Where to look in code

| If you want to...                                              | Read                                                          |
| -------------------------------------------------------------- | ------------------------------------------------------------- |
| Change the parse → extract → embed → reduce stages on NSO docs | [`packages/curator/stages.py`](packages/curator/stages.py)    |
| Switch from local SBERT to NIM hosted embeddings               | [`packages/personas/embed/backends.py`](packages/personas/embed/backends.py) |
| Replay this notebook on the **full** 300K small parquet        | bump `SAMPLE_FRAC = 1.00` in §1                               |
| Run the same flow against the **3M large** parquet             | swap `SMALL_VI` / `SMALL_EN` for the `-large-` paths in §1    |
| Regenerate the four parquets from scratch                      | `python -m packages.pipeline.cli build-nemotron`              |

See [`DATASYNTHESIS.md`](DATASYNTHESIS.md) for the conceptual
walkthrough and [`DATASETS.md`](DATASETS.md) for the schema definition
and source-of-truth Python identifiers.